### ISSUE TITLE
Version 8.0.0 adds pytz dependency which is deprecated

### ISSUE THREAD

**Issue by Enkelena** [Fetchered/time_decode#13]
You recently added pytz as a dependency to release 8.0.0.
Referring to https://github.com/pganssle/pytz-deprecation-shim "_pytz has served the Python community well for many years, but it is no longer the best option for providing time zones. pytz has a non-standard interface that is [very easy to misuse](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html); this interface was necessary when pytz was created, because datetime had no way to represent ambiguous datetimes, but this was solved in Python 3.6, which added a fold attribute to datetimes in [PEP 495](https://www.python.org/dev/peps/pep-0495/). With the addition of the zoneinfo module in Python 3.9 ([PEP 615](https://www.python.org/dev/peps/pep-0615/)), there has never been a better time to migrate away from pytz¨"_
 
pytz is deprecated in Debian since Debian 10, therefore version 8.0.0 of time-decode can not be uploaded as is.
I can patch the source code to use python3-pytz-deprecation-shim but would prefer to not have to patch it at all.

Could you consider to use the standard python3 functions instead of pytz?

**Comment by digitalsleuth** [comment]
Hi @Enkelena , thanks for reaching out! Yes, pytz is deprecated for Python 3.9 and above, however it is still being used and maintained for lower versions of python, such as 3.8 which is the default in Ubuntu 20.04 LTS. Given that this LTS is supported for another year, I opted to add pytz momentarily. I am adding an update shortly which will use ZoneInfo as well, as it was added to the base library in 3.9.

The installation process will then determine the running version of python and install / change the requirements accordingly. I've been a bit busy the last couple of days, but hope to have this released in the next 24 hours.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @Enkelena , just wanted to give you a heads up that I've made some updates to the tool, but haven't completed unit tests on the changes. I'm incorporating a way to only require pytz if the OS doesn't support the native zoneinfo. It's in the branch `pytz_replace`, but it is not ready for release. 

I know I said 24 hours, but unfortunately things have been a bit busy this week. I am going on vacation in the morning, but I will get to this as soon as I can.

Cheers

**Comment by Enkelena** [comment]
Hi @digitalsleuth  thanks for letting me know. Enjoy your holiday! Thanks for starting to work on it, I will wait for your release.

**Comment by digitalsleuth** [comment]
Took a while for me to get back to this, but this issue has now been resolved with [v9.0.0](https://github.com/digitalsleuth/time_decode/releases/tag/v9.0.0). Cheers, and thanks again for pointing this out!

**Comment by Enkelena** [comment]
@digitalsleuth, thanks for your fixes! The time-decode package resides at [time-decode - Debian Tracker](https://tracker.debian.org/pkg/time-decode) and is currently on version 9.0.0. Looking forward to future releases!

**Comment by digitalsleuth** [comment]
Hi @Enkelena , I've released v10 recently which addresses some issues with `.localize`, and adds more refinements to the time zone data. Cheers!

**Comment by Enkelena** [comment]
hi @digitalsleuth v10.3.1 has been uploaded to Debian unstable and should migrate to Debian Testing in 5 days.

Since tzdata is not packaged as a python module in Debian (https://pypi.org/project/tzdata/), I patched your tzdata_timezones() function as below to use system timezones instead:
```

 def tzdata_timezones():
-    """Get the tzdata timezones and put them in a list for the timezone drop-down"""
-    zoneinfo_dir = os.path.join(tzdata.__path__[0], "zoneinfo")
-    timezones = set()
-    for root, _, files in os.walk(zoneinfo_dir):
-        for name in files:
-            rel_path = os.path.relpath(os.path.join(root, name), zoneinfo_dir)
-            if rel_path.startswith(("posix", "right")):
-                continue
-            timezones.add(rel_path)
-    return sorted(timezones)
+    """Return available system timezones for the dropdown"""
+    return sorted(
+        tz for tz in available_timezones()
+        if not tz.startswith(("posix", "right"))
+    )
```
https://salsa.debian.org/pkg-security-team/time-decode/-/blob/debian/master/debian/patches/Replace-tzdata-import-with-zoneinfo.available_timezones.patch

**Comment by digitalsleuth** [comment]
Hi @Enkelena , thanks for the heads up. I'll add a way to mitigate this in the future as well. Also, as an FYI, I'll be adding a couple more timestamps soon and some bug fixes in the next release. Cheers!

**Comment by digitalsleuth** [comment]
Hi @Enkelena , just a follow up. When you attempt to run it on Debian, do you get a python import error, or is it a package / OS error? Just looking to add some error / import handling where necessary and it would be helpful to identify the best way to detect what you're seeing. Thanks!

**Comment by Enkelena** [comment]
@digitalsleuth an import error.  See below:

time-decode --help
```
Traceback (most recent call last):
  File "/usr/bin/time-decode", line 5, in <module>
    from time_decode.time_decode import main
  File "/usr/lib/python3/dist-packages/time_decode/time_decode.py", line 25, in <module>
    import tzdata
ModuleNotFoundError: No module named 'tzdata'
```
And while building:
`I: dh_python3 pydist:399: Cannot find package that provides tzdata. Please add package that provides it to Build-Depends or add "tzdata python3-tzdata" line to debian/py3dist-overrides or add proper dependency to Depends by hand and ignore this info.`

**Comment by digitalsleuth** [comment]
Hi @Enkelena , released version 10.4.0 which addresses the tzdata issue. Hopefully this helps!
